config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "matches#index"
  resources :matches do
    resources :match_maker, only: %i[create edit update]
  end

  resources :match_maker, only: %i[destroy]

end

app/views/layouts/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Criar Partida", new_match_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link", data: { turbo_method: :delete, confirm: "Você tem certeza que deseja sair?" }, :turbo => "frame-bottom" %>

          </li>
        <% else %>
          <li class="nav-item active">
              <%= link_to "Registre-se", new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
              <%= link_to "Log in", user_session_path, class: "nav-link" %>
          </li>
        <% end %>
          <li class="nav-item dropdown">
            <%= link_to "Menu","#", class: "nav-link", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Criar Partida",  new_match_path, class: "dropdown-item" %>
              <%= link_to "Minhas Partidas", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
      </ul>
    </div>
  </div>
</div>